
name: goreleaser-slsa
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Adjust if needed

      - name: Install SLSA Verifier
        uses: slsa-framework/slsa-github-generator/.github/actions/installer@v1.9.0

      - name: Run GoReleaser with SLSA
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --provenance

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional: Verify SLSA provenance
      - name: Verify SLSA provenance
        run: |
          ./slsa-verifier verify-artifact --provenance-path dist/*.intoto.jsonl --source-uri github.com/${{ github.repository }}
