apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kandji-cloudflare-syncer.fullname" . }}-config
  labels:
    {{- include "kandji-cloudflare-syncer.labels" . | nindent 4 }}

data:
  config.yaml: |
{{ .Values.config.data | indent 4 }}
