apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kandji-cloudflare-syncer.fullname" . }}
  labels:
    {{- include "kandji-cloudflare-syncer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kandji-cloudflare-syncer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kandji-cloudflare-syncer.selectorLabels" . | nindent 8 }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecret }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kandji-cloudflare-syncer.serviceAccountName" . }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.args }}
          args:
            {{- range .Values.args }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          env:
            - name: KANDJI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "kandji-cloudflare-syncer.fullname" . }}-secrets
                  key: KANDJI_API_TOKEN
            - name: TELEPORT_IDENTITY_FILE
              value: /app/identity.pem
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
            - name: teleport-identity
              mountPath: /app/identity.pem
              subPath: identity.pem
              readOnly: true
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "kandji-cloudflare-syncer.fullname" . }}-config
        - name: teleport-identity
          secret:
            secretName: {{ include "kandji-cloudflare-syncer.fullname" . }}-identity
            items:
              - key: auth_id
                path: identity.pem
