name: Semantic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  actions: read
  
jobs:
  semantic-release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Prepare prerelease semantic
        if: github.ref != 'refs/heads/main'
        run: mv .releaserc.prerelease.yaml .releaserc.yaml

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # SLSA builder job
  slsa-build:
    needs: semantic-release
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.0.0
    with:
      go-version: "1.23"

  create-release:
    needs: slsa-build
    runs-on: ubuntu-latest
    steps:
      - name: Download SLSA build artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact  # or whatever the SLSA job outputs

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: "path/to/artifacts/*"  # Adjust path as needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
