name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Prepare prerelease semantic
        if: github.ref != 'refs/heads/main'
        run: mv .releaserc.prerelease.yaml .releaserc.yaml

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  build-binaries:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.set-artifact-path.outputs.path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/app-linux-amd64 .
          GOOS=darwin GOARCH=amd64 go build -o dist/app-darwin-amd64 .

      - name: Set artifact path
        id: set-artifact-path
        run: echo "path=dist/" >> $GITHUB_OUTPUT

  generate-slsa-provenance:
    needs: build-binaries
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.0.0
    with:
      go-version: "1.23"
      base-image: "ubuntu-latest"
      artifact-path: ${{ needs.build-binaries.outputs.artifact-path }}

  create-release:
    needs: build-binaries
    runs-on: ubuntu-latest
    steps:
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
